# Generated by Django 6.0.1 on 2026-01-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='generos',
            field=models.ManyToManyField(blank=True, help_text='Una película puede pertenecer a múltiples géneros', related_name='peliculas', to='movies.genre'),
        ),
    ]
