# Generated by Django 6.0.1 on 2026-01-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_genre_movie_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duracion',
            field=models.IntegerField(help_text='Duración en segundos (ej: 5430 = 1:30:30)'),
        ),
    ]
