# Generated by Django 6.0.1 on 2026-01-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_duracion'),
    ]

    operations = [
        migrations.RunSQL(
            'DROP TABLE IF EXISTS movies_remembertoken;',
            'CREATE TABLE movies_remembertoken (id INTEGER PRIMARY KEY);'
        ),
    ]
