# Generated by Django 6.0.1 on 2026-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_delete_remembertoken_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='año_publicacion',
            field=models.IntegerField(blank=True, help_text='Año de publicación de la película', null=True),
        ),
    ]
